import { PageShell } from '@lib/components/PageShell'
import { Section } from '@lib/components/Section'
import { CodeBlock } from '@lib/components/schematic/CodeBlock'
import { FnChip } from '@lib/components/schematic/FnChip'
import { Highlight, HighlightStyles } from '@lib/content/highlight'
import { HARNESS_TRIGGERS } from '../content/harness'

const CODEGEN_YML = `# generate a typed harness client
src/iii/harness.ts:
  language: typescript
  mode: ["types", "functions", "triggers"]
  workers: ["harness"]
  functions: ["harness::*"]
  triggers: ["harness"]
  iii_instance:
    type: import
    path: "@/services/iii"
    name: iii`

const GENERATED_TS = `// code generated by iii codegen · do not edit

export const harness = {
  async send(input: SendInput): Promise<SendResult> { /* ... */ },
  async cancel(input: CancelInput): Promise<CancelResult> { /* ... */ },

  // mode: triggers, bind harness::turn-completed, fully typed
  onTurnCompleted(
    config: TurnCompletedConfig,
    handler: (turn: TurnCompletedPayload) => Promise<void>,
  ): Trigger { /* ... */ },
}`

const CHAT_TS = `import { harness } from '@/iii/harness'

// fire a turn, input and result are typed
const { session_id } = await harness.send({ message: 'summarise the repo readme' })

// react when the turn finishes: typed config + payload
harness.onTurnCompleted({ session_id }, async (turn) => {
  render(turn.result)
})`

/**
 * A14 - deep-dive page. The full walkthrough of building a typed consumer on
 * top of harness: the config, the generated surface, the consumer code, and the
 * complete trigger surface codegen can bind. Code blocks use the same rainbow
 * highlighter as the languages section.
 */
export function HarnessConsumerPage() {
  return (
    <PageShell
      eyebrow="deep dive"
      title="build a typed harness consumer"
      description="harness is a turn loop you talk to over functions and triggers. point codegen at it once and you get a typed client: call harness.send() with no bare strings, and bind harness::turn-completed via a typed harness.onTurnCompleted handler."
    >
      <HighlightStyles />

      <Section
        id="hc-config"
        index="01"
        eyebrow="the config"
        title="one output, scoped to harness."
        lede="types, function wrappers, and trigger helpers for everything under harness::*, written to one typescript file that imports your shared iii client."
      >
        <CodeBlock title="codegen.yml">
          <Highlight code={CODEGEN_YML} lang="yaml" />
        </CodeBlock>
      </Section>

      <Section
        id="hc-generated"
        index="02"
        eyebrow="the generated client"
        title="functions and a typed on-handler."
        lede="every harness function becomes a method on a harness namespace object that lowers to iii.trigger; every trigger type becomes a typed registration helper on the same object."
      >
        <CodeBlock title="src/iii/harness.ts (generated)">
          <Highlight code={GENERATED_TS} lang="typescript" />
        </CodeBlock>
      </Section>

      <Section
        id="hc-consumer"
        index="03"
        eyebrow="your consumer"
        title="send a turn, render the result."
        lede="no function_id strings, no any-typed payloads. a renamed field in harness is now a build error in this file."
      >
        <CodeBlock title="chat.ts">
          <Highlight code={CHAT_TS} lang="typescript" />
        </CodeBlock>
      </Section>

      <Section
        id="hc-surface"
        index="04"
        eyebrow="the full surface"
        title="seven trigger types, all bindable."
        lede="mode: triggers generates a typed helper for each. two async events fan out to consumers; five sync hooks let operator-trusted siblings shape a turn in-path."
      >
        <div className="overflow-x-auto">
          <div className="border border-rule bg-rule grid grid-cols-1 gap-px min-w-[440px]">
            <div className="bg-panel px-4 py-2.5 grid grid-cols-[minmax(0,1fr)_auto] gap-x-4 font-mono text-[10px] uppercase tracking-[0.14em] text-ink-faint">
              <span>trigger type</span>
              <span>kind</span>
            </div>
            {HARNESS_TRIGGERS.map((t) => (
              <div key={t.id} className="bg-bg px-4 py-3.5">
                <div className="grid grid-cols-[minmax(0,1fr)_auto] gap-x-4 items-center">
                  <FnChip tone="ink">{t.id}</FnChip>
                  <span className="font-mono text-[10px] uppercase tracking-[0.06em] text-ink-faint whitespace-nowrap">
                    {t.kind}
                  </span>
                </div>
                <p className="mt-1.5 font-mono text-[12px] leading-[1.6] text-ink-faint lowercase">{t.fires}</p>
              </div>
            ))}
          </div>
        </div>
      </Section>
    </PageShell>
  )
}
