import { Section } from '@lib/components/Section'
import { CodeBlock } from '@lib/components/schematic/CodeBlock'
import { ModeToggle } from '@lib/components/schematic/ModeToggle'
import { Highlight, HighlightStyles } from '@lib/content/highlight'
import { useState } from 'react'

type CodeLang = 'typescript' | 'javascript' | 'rust' | 'python'

interface LangOut {
  file: string
  instance: string
  code: string
}

const OUTPUTS: Record<CodeLang, LangOut> = {
  typescript: {
    file: 'src/iii/harness.ts',
    instance: 'iii_instance: import',
    code: `// generated by iii codegen · do not edit
import { iii } from '@/services/iii'

export interface SendInput {
  message: string
  model?: string
  provider?: string
}
export interface SendResult {
  session_id: string
  turn_id: string
  accepted: boolean
}

export const harness = {
  async send(input: SendInput): Promise<SendResult> {
    return iii.trigger<SendInput, SendResult>({
      function_id: 'harness::send',
      payload: input,
    })
  },
}`,
  },
  rust: {
    file: 'src/iii/harness.rs',
    instance: 'iii_instance: import',
    code: `// generated by iii codegen · do not edit
use crate::services::iii::iii;
use iii_sdk::{IIIError, protocol::TriggerRequest};

pub type Result<T> = std::result::Result<T, IIIError>;

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct SendInput {
    pub message: String,
    pub model: Option<String>,
    pub provider: Option<String>,
}
#[derive(Serialize, Deserialize, JsonSchema)]
pub struct SendResult {
    pub session_id: String,
    pub turn_id: String,
    pub accepted: bool,
}

pub mod harness {
    use super::*;

    pub async fn send(input: SendInput) -> Result<SendResult> {
        let value = iii.trigger(TriggerRequest {
            function_id: "harness::send".to_string(),
            payload: serde_json::to_value(input)?,
            action: None,
            timeout_ms: None,
        }).await?;
        Ok(serde_json::from_value(value)?)
    }
}`,
  },
  python: {
    file: 'src/iii/harness.py',
    instance: 'iii_instance: import',
    code: `# generated by iii codegen · do not edit
from services.iii import iii
from pydantic import BaseModel

class SendInput(BaseModel):
    message: str
    model: str | None = None
    provider: str | None = None

class SendResult(BaseModel):
    session_id: str
    turn_id: str
    accepted: bool

class harness:
    @staticmethod
    def send(input: SendInput) -> SendResult:
        result = iii.trigger({
            "function_id": "harness::send",
            "payload": input.model_dump(by_alias=True),
        })
        return SendResult.model_validate(result)`,
  },
  javascript: {
    file: 'src/iii/harness.js',
    instance: 'iii_instance: import',
    code: `// generated by iii codegen · do not edit
import { iii } from '@/services/iii'

/** @typedef {{ message: string, model?: string, provider?: string }} SendInput */
/** @typedef {{ session_id: string, turn_id: string, accepted: boolean }} SendResult */

/**
 * @param {SendInput} input
 * @returns {Promise<SendResult>}
 */
export const harness = {
  async send(input) {
    return iii.trigger({ function_id: 'harness::send', payload: input })
  },
}`,
  },
}

const LANG_OPTIONS: { value: CodeLang; label: string }[] = [
  { value: 'typescript', label: 'typescript' },
  { value: 'rust', label: 'rust' },
  { value: 'python', label: 'python' },
  { value: 'javascript', label: 'javascript' },
]

/**
 * A13 - code walkthrough with language tabs. One function, harness::send,
 * generated four ways from the same iii_instance: import config. The tab is the
 * interaction; each tab is the verbatim wrapper that lowers to a single
 * iii.trigger call in that language's idiom, syntax-highlighted in the deck's
 * keyword / string / comment scheme.
 */
export function LanguagesSection() {
  const [lang, setLang] = useState<CodeLang>('typescript')
  const out = OUTPUTS[lang]

  return (
    <Section
      id="languages"
      index="06"
      eyebrow="every language"
      title="same catalog. idiomatic code in every language."
      lede="harness::send, generated four ways from the one schema. the type, the wrapper, and the iii.trigger call it lowers to, each in the target language's idiom."
    >
      <HighlightStyles />
      <div className="flex flex-col gap-4 @3xl:flex-row @3xl:items-center @3xl:justify-between">
        <ModeToggle value={lang} onChange={setLang} options={LANG_OPTIONS} />
        <span className="font-mono text-[11px] uppercase tracking-[0.06em] text-ink-faint">{out.instance}</span>
      </div>

      <div className="mt-5">
        <CodeBlock title={out.file}>
          <Highlight code={out.code} lang={lang} />
        </CodeBlock>
      </div>

      <p className="mt-5 font-mono text-[12px] leading-[1.6] text-ink-faint lowercase max-w-[76ch]">
        every tab uses the same config: <span className="text-ink">iii_instance: import</span>. each wrapper pulls in
        your shared iii client and reads <span className="text-ink">harness.send(input)</span>, so only the language
        idiom changes. the alternative, <span className="text-ink">iii_instance: argument</span>, takes the client as a
        first parameter instead.
      </p>
    </Section>
  )
}
