// Copyright Motia LLC and/or licensed to Motia LLC under one or more
// contributor license agreements. Licensed under the Elastic License 2.0;
// you may not use this file except in compliance with the Elastic License 2.0.
// This software is patent protected. We welcome discussions - reach out at team@iii.dev
// See LICENSE and PATENTS files for details.

//! Wire protocol for the host↔guest shell-exec channel.
//!
//! Separate from the supervisor control channel (`protocol.rs`) because
//! exec-style sessions need **multiplexing** — several concurrent
//! sessions interleave on the same virtio-console port — while the
//! control channel is strictly one-request-at-a-time. Multiplexing
//! requires a correlation id on every frame, so we switch from the
//! newline-delimited JSON that the control channel uses to a
//! length-prefixed binary frame with a JSON payload.
//!
//! Frame wire format (big-endian throughout):
//!
//! ```text
//! ┌──────────┬──────────┬───────┬──────────────────┐
//! │ frame_len│ corr_id  │ flags │  JSON payload    │
//! │  u32     │  u32     │  u8   │  frame_len-5 B   │
//! └──────────┴──────────┴───────┴──────────────────┘
//!   4 bytes    4 bytes   1 byte    variable
//! ```
//!
//! - `frame_len` counts everything after itself (`corr_id + flags +
//!   payload`). `FRAME_HEADER_SIZE` is the fixed 5 bytes for
//!   `corr_id + flags`, so the payload length is `frame_len - 5`.
//! - `corr_id` is generated by the host client; the guest echoes it on
//!   every response frame so a stateless relay can route by id without
//!   parsing JSON.
//! - `flags` currently carries `FLAG_TERMINAL` only; more can be added
//!   without a protocol rev since the field is a bitfield.
//! - Payload is UTF-8 JSON, one `ShellMessage` per frame.
//!
//! Max frame size is [`MAX_FRAME_SIZE`] (4 MiB), matching microsandbox's
//! ceiling so a wedged session can't OOM the host relay.

use serde::{Deserialize, Serialize};

/// Virtio-console port name used to carry the shell-exec channel.
/// Set host-side via `ConsoleBuilder::port("iii.exec", ...)` and
/// discovered guest-side by walking `/sys/class/virtio-ports/*/name`.
pub const SHELL_PORT_NAME: &str = "iii.exec";

/// Length of the fixed-size header that follows `frame_len`: 4-byte
/// `corr_id` + 1-byte `flags`. Payload length = `frame_len - FRAME_HEADER_SIZE`.
pub const FRAME_HEADER_SIZE: usize = 5;

/// Hard cap on the total bytes of `corr_id + flags + payload` per frame.
/// Matches microsandbox's 4 MiB ceiling. Prevents a wedged peer from
/// asking the reader to allocate an arbitrary buffer.
pub const MAX_FRAME_SIZE: usize = 4 * 1024 * 1024;

/// Bitmask flags carried in the 1-byte header field.
pub mod flags {
    /// This frame ends the session with `corr_id`. Relays/dispatchers
    /// may GC per-session state after observing it. Always set on
    /// [`ShellMessage::Exited`] and on [`ShellMessage::Error`] when the
    /// error is fatal (e.g. spawn failure with no follow-up).
    pub const FLAG_TERMINAL: u8 = 0x01;
}

/// Single directory entry returned by `FsOp::Ls` / `FsOp::Stat`.
/// `mode` is the octal permission string (e.g. `"0644"`); `mtime` is
/// Unix seconds. `is_symlink` reflects the entry itself — FS handlers
/// never follow symlinks unless the op doc-comment says otherwise.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct FsEntry {
    pub name: String,
    pub is_dir: bool,
    pub size: u64,
    pub mode: String,
    pub mtime: i64,
    pub is_symlink: bool,
}

/// Single grep hit. `line` is 1-based. `content` is already truncated
/// to `max_line_bytes` (with a trailing `…`) if the original line was
/// longer.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct FsMatch {
    #[serde(alias = "file")]
    pub path: String,
    pub line: u64,
    pub content: String,
}

/// One `sed` file-level outcome. `success=false` carries the human
/// failure message in `error`; otherwise `error` is absent.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct FsSedFileResult {
    #[serde(alias = "file")]
    pub path: String,
    pub replacements: u64,
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub error: Option<String>,
}

/// Body of an `FsRequest` frame. Tagged on `op` so a new op can be
/// added without a protocol rev (old peers reply with
/// `FsError { code: "S219" }` because `deny_unknown_fields` rejects
/// unknown tags).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "op", rename_all = "snake_case", deny_unknown_fields)]
pub enum FsOp {
    Ls {
        path: String,
    },
    Stat {
        path: String,
    },
    Mkdir {
        path: String,
        mode: String,
        parents: bool,
    },
    /// Upload: start of a chunked write. Followed by N `FsChunk`
    /// frames and a terminal `FsEnd`.
    WriteStart {
        path: String,
        mode: String,
        parents: bool,
    },
    /// Download: start of a chunked read. Supervisor responds with
    /// `FsMeta` then streams N `FsChunk` frames and a terminal
    /// `FsEnd`.
    ReadStart {
        path: String,
    },
    Rm {
        path: String,
        recursive: bool,
    },
    Chmod {
        path: String,
        mode: String,
        #[serde(default)]
        uid: Option<u32>,
        #[serde(default)]
        gid: Option<u32>,
        recursive: bool,
    },
    Mv {
        src: String,
        dst: String,
        overwrite: bool,
    },
    Grep {
        path: String,
        pattern: String,
        recursive: bool,
        ignore_case: bool,
        include_glob: Vec<String>,
        exclude_glob: Vec<String>,
        max_matches: u64,
        max_line_bytes: u64,
    },
    /// Apply a find-and-replace.
    ///
    /// Caller must provide **exactly one** of:
    /// - `files` — explicit list of paths to rewrite (legacy form;
    ///   non-empty vec).
    /// - `path` + optional `recursive` / `include_glob` / `exclude_glob`
    ///   — walk a tree like grep does and rewrite every matching file.
    ///   `path` may be a directory, a regular file, or a symlink to
    ///   either (symlink-to-dir is resolved before walking).
    ///   `recursive=false` on a directory is rejected with `S210`,
    ///   matching grep — pass `files: [...]` instead, or use
    ///   `recursive=true` with a tighter `include_glob`.
    ///
    /// Both forms produce per-file atomic temp+rename writes. The handler
    /// returns `FsError { code: "S210" }` if both or neither form is
    /// supplied (validated in the worker before the wire call). Old
    /// guests that only know the legacy form keep working because the
    /// new fields are `#[serde(default)]`.
    Sed {
        #[serde(default)]
        files: Vec<String>,
        #[serde(default)]
        path: Option<String>,
        #[serde(default = "default_recursive_true")]
        recursive: bool,
        #[serde(default)]
        include_glob: Vec<String>,
        #[serde(default)]
        exclude_glob: Vec<String>,
        pattern: String,
        replacement: String,
        regex: bool,
        first_only: bool,
        ignore_case: bool,
    },
}

fn default_recursive_true() -> bool {
    true
}

/// Body of an `FsResponse` frame. One variant per op. Errors do not
/// come back as `FsResult`; they come back as `FsError`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum FsResult {
    Ls {
        entries: Vec<FsEntry>,
    },
    Stat(FsEntry),
    Mkdir {
        created: bool,
    },
    /// Terminal response of a `WriteStart` sequence. Always carries
    /// the final byte count fsync'd to the target path.
    Write {
        bytes_written: u64,
        path: String,
    },
    Rm {
        removed: bool,
    },
    Chmod {
        updated: u64,
    },
    Mv {
        moved: bool,
    },
    Grep {
        matches: Vec<FsMatch>,
        truncated: bool,
    },
    Sed {
        results: Vec<FsSedFileResult>,
        total_replacements: u64,
    },
}

/// Metadata frame sent by the supervisor at the start of a
/// `ReadStart` sequence (one per session, before any `FsChunk`).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct FsReadMeta {
    pub size: u64,
    pub mode: String,
    pub mtime: i64,
}

/// One shell-channel message. Wire JSON uses an internal `t` tag so
/// extra variants can be added without breaking existing decoders (a
/// peer that sees an unknown tag gets a serde error and the relay
/// forwards an `Error` frame back).
///
/// Variants that carry binary payloads (`Stdin`, `Stdout`, `Stderr`)
/// transport bytes as base64 inside JSON — costs ~33% bandwidth vs
/// raw bytes, which we accept for MVP to keep the codec dependency-
/// free. Swapping to CBOR later only touches this module.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "t", rename_all = "snake_case")]
pub enum ShellMessage {
    /// Host → guest: spawn a child process under this correlation id.
    /// Exactly one per session, sent first.
    Request {
        /// Program path (not searched on PATH by the dispatcher —
        /// callers pass the absolute path or rely on the guest shell
        /// to do path resolution, e.g. `cmd = "/bin/sh"`, `args =
        /// ["-c", "ls /"]`).
        cmd: String,
        /// Arguments passed to `cmd`. Empty vec means no args.
        args: Vec<String>,
        /// Environment variable overrides in `KEY=VALUE` form. The
        /// dispatcher starts from the guest init's environment and
        /// layers these on top.
        env: Vec<String>,
        /// Working directory for the spawned child. `None` inherits
        /// the dispatcher's cwd (typically `/workspace`).
        cwd: Option<String>,
        /// Allocate a pseudo-terminal. When true, stdout and stderr
        /// are merged through the PTY master and the client is
        /// expected to be in raw mode. When false, stdout and stderr
        /// come back on their own variants (pipe mode).
        tty: bool,
        /// Initial PTY row count. Ignored unless `tty` is true.
        rows: u16,
        /// Initial PTY column count. Ignored unless `tty` is true.
        cols: u16,
    },
    /// Guest → host: child successfully spawned, report its pid.
    /// Sent exactly once per session, before any Stdout/Stderr.
    Started {
        /// Guest-side pid of the spawned child.
        pid: u32,
    },
    /// Host → guest: bytes to write to the child's stdin. Empty
    /// `data_b64` (decoded: zero bytes) signals EOF — the dispatcher
    /// closes the child's stdin after flushing.
    Stdin {
        /// Base64-encoded bytes. Empty string ⇒ EOF.
        data_b64: String,
    },
    /// Guest → host: bytes the child wrote to stdout.
    Stdout {
        /// Base64-encoded bytes.
        data_b64: String,
    },
    /// Guest → host: bytes the child wrote to stderr. Only sent in
    /// pipe mode — TTY sessions merge stderr into Stdout.
    Stderr {
        /// Base64-encoded bytes.
        data_b64: String,
    },
    /// Guest → host: child has exited. Always sent with
    /// [`flags::FLAG_TERMINAL`] set. No further frames will arrive on
    /// this correlation id.
    Exited {
        /// Child's exit code, or `128 + signal` for signal-terminated
        /// processes (matches shell convention).
        code: i32,
    },
    /// Host → guest: window size change. Only meaningful in TTY mode.
    Resize {
        /// New row count.
        rows: u16,
        /// New column count.
        cols: u16,
    },
    /// Host → guest: deliver a signal to the running child.
    Signal {
        /// POSIX signal number (e.g. 15 for SIGTERM, 9 for SIGKILL).
        signal: i32,
    },
    /// Guest → host: dispatcher-side failure (spawn failed, child
    /// setup ioctl failed, PTY allocation failed, …). Usually
    /// accompanied by [`flags::FLAG_TERMINAL`] when fatal.
    Error {
        /// Human-readable failure description. The host surfaces this
        /// to the user and translates to a nonzero exit code.
        message: String,
    },
    /// Host → guest: run a filesystem operation under this
    /// correlation id. For one-shot ops (ls, stat, mkdir, rm, chmod,
    /// mv, grep, sed) the guest replies with `FsResponse` (terminal)
    /// or `FsError` (terminal). For `WriteStart`, the host sends N
    /// `FsChunk` frames followed by `FsEnd`, and the guest replies
    /// with `FsResponse { Write { .. } }` (terminal). For
    /// `ReadStart`, the guest replies with `FsMeta`, N `FsChunk`
    /// frames, and a terminal `FsEnd`.
    FsRequest(FsOp),
    /// Guest → host: metadata for a download. Sent exactly once at
    /// the start of a `ReadStart` session, before any `FsChunk`.
    FsMeta(FsReadMeta),
    /// Host ↔ guest: raw bytes of a streamed upload (host → guest)
    /// or download (guest → host). `data_b64` is base64-encoded for
    /// JSON transport; producers should chunk at 64 KiB to match III
    /// data-channel framing and stay safely under MAX_FRAME_SIZE.
    FsChunk {
        /// Base64-encoded bytes.
        data_b64: String,
    },
    /// Host ↔ guest: terminal frame of a chunked upload/download
    /// sequence. Always sent with `FLAG_TERMINAL`. For `WriteStart`
    /// this flows host → guest and triggers the supervisor's
    /// fsync+rename. For `ReadStart` this flows guest → host and
    /// closes the session.
    FsEnd,
    /// Guest → host: terminal response carrying the op result.
    /// Always sent with `FLAG_TERMINAL`.
    FsResponse(FsResult),
    /// Guest → host: terminal error frame carrying an S21x code.
    /// Always sent with `FLAG_TERMINAL`.
    FsError { code: String, message: String },
}

/// Encoding/decoding errors for the shell-channel frame codec.
#[derive(Debug, thiserror::Error)]
pub enum ShellCodecError {
    /// A frame's declared length was smaller than the fixed header or
    /// larger than [`MAX_FRAME_SIZE`]. The reader should treat this as
    /// a protocol violation and close the channel.
    #[error("frame length {0} out of range (must be {FRAME_HEADER_SIZE}..={MAX_FRAME_SIZE})")]
    InvalidFrameLength(usize),
    /// JSON serialization of a [`ShellMessage`] failed. Should never
    /// happen for values produced by this crate; forwarded through in
    /// case a downstream embedder adds a custom variant that serde
    /// rejects.
    #[error("json serialize: {0}")]
    Serialize(#[source] serde_json::Error),
    /// JSON deserialization of the payload bytes failed. Wire payload
    /// was not a recognized `ShellMessage`.
    #[error("json deserialize: {0}")]
    Deserialize(#[source] serde_json::Error),
    /// Payload bytes length did not match the declared header
    /// length. Only returned by [`decode_frame_body`]; the async
    /// read path reads an exact number of bytes and can't hit this.
    #[error("payload length mismatch: header says {declared}, got {actual}")]
    LengthMismatch {
        /// Length the header claimed.
        declared: usize,
        /// Length the caller actually supplied.
        actual: usize,
    },
}

/// Encode a message as a full wire frame, ready to write in one shot.
///
/// Returns a heap-allocated `Vec<u8>` that starts with the 4-byte
/// `frame_len` prefix. Callers that want to avoid the allocation can
/// use [`encode_frame_into`] to append to an existing buffer instead.
pub fn encode_frame(
    corr_id: u32,
    flags: u8,
    msg: &ShellMessage,
) -> Result<Vec<u8>, ShellCodecError> {
    let mut buf = Vec::with_capacity(64);
    encode_frame_into(&mut buf, corr_id, flags, msg)?;
    Ok(buf)
}

/// Append a wire frame to `buf`. Same output as [`encode_frame`] but
/// reuses the caller's allocation — useful inside a tight write loop
/// that batches frames together before flushing to the socket.
pub fn encode_frame_into(
    buf: &mut Vec<u8>,
    corr_id: u32,
    flags: u8,
    msg: &ShellMessage,
) -> Result<(), ShellCodecError> {
    let payload = serde_json::to_vec(msg).map_err(ShellCodecError::Serialize)?;
    let frame_len = FRAME_HEADER_SIZE + payload.len();
    if frame_len > MAX_FRAME_SIZE {
        return Err(ShellCodecError::InvalidFrameLength(frame_len));
    }
    buf.reserve(4 + frame_len);
    buf.extend_from_slice(&(frame_len as u32).to_be_bytes());
    buf.extend_from_slice(&corr_id.to_be_bytes());
    buf.push(flags);
    buf.extend_from_slice(&payload);
    Ok(())
}

/// Decode the bytes that follow the `frame_len` prefix. Input must be
/// exactly `corr_id (4) + flags (1) + payload (N)` bytes.
///
/// Splits out as a separate function so both sync and async readers
/// share the same parsing step: they read `frame_len` themselves,
/// slurp the body, then hand it here.
pub fn decode_frame_body(body: &[u8]) -> Result<(u32, u8, ShellMessage), ShellCodecError> {
    if body.len() < FRAME_HEADER_SIZE {
        return Err(ShellCodecError::LengthMismatch {
            declared: FRAME_HEADER_SIZE,
            actual: body.len(),
        });
    }
    let corr_id = u32::from_be_bytes([body[0], body[1], body[2], body[3]]);
    let flags = body[4];
    let payload = &body[FRAME_HEADER_SIZE..];
    let msg = serde_json::from_slice(payload).map_err(ShellCodecError::Deserialize)?;
    Ok((corr_id, flags, msg))
}

/// Validate a declared `frame_len` read from the length prefix.
/// Returns `Ok(payload_len)` on success so the caller can size its
/// payload buffer in one shot.
pub fn validate_frame_len(frame_len: u32) -> Result<usize, ShellCodecError> {
    let frame_len = frame_len as usize;
    if !(FRAME_HEADER_SIZE..=MAX_FRAME_SIZE).contains(&frame_len) {
        return Err(ShellCodecError::InvalidFrameLength(frame_len));
    }
    Ok(frame_len)
}

/// Read a single frame from a blocking reader. Returns
/// `Ok(None)` on clean EOF at a frame boundary (peer closed the
/// channel between frames), `Err` on partial reads or malformed
/// framing.
pub fn read_frame_blocking<R: std::io::Read>(
    reader: &mut R,
) -> Result<Option<(u32, u8, ShellMessage)>, std::io::Error> {
    let mut len_buf = [0u8; 4];
    match read_full(reader, &mut len_buf)? {
        ReadOutcome::EofAtBoundary => return Ok(None),
        ReadOutcome::Partial => {
            return Err(std::io::Error::new(
                std::io::ErrorKind::UnexpectedEof,
                "partial frame length prefix",
            ));
        }
        ReadOutcome::Full => {}
    }
    let frame_len = u32::from_be_bytes(len_buf);
    let frame_len = validate_frame_len(frame_len)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e.to_string()))?;

    // SAFETY: read_exact fills every byte of the uninit body before
    // decode_frame_body sees it; on error we truncate + drop. u8 has
    // no invalid bit patterns. Matches shell_relay::read_frame.
    let mut body: Vec<u8> = Vec::with_capacity(frame_len);
    unsafe { body.set_len(frame_len) };
    if let Err(e) = reader.read_exact(&mut body) {
        body.truncate(0);
        return Err(e);
    }
    let parsed = decode_frame_body(&body)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e.to_string()))?;
    Ok(Some(parsed))
}

/// Write a single frame to a blocking writer. Does not flush; the
/// caller controls batching.
pub fn write_frame_blocking<W: std::io::Write>(
    writer: &mut W,
    corr_id: u32,
    flags: u8,
    msg: &ShellMessage,
) -> Result<(), std::io::Error> {
    let frame = encode_frame(corr_id, flags, msg)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e.to_string()))?;
    writer.write_all(&frame)
}

/// Outcome of [`read_full`] — distinguishes "clean EOF between frames"
/// from "EOF mid-frame" so the frame reader can treat the first as
/// graceful shutdown.
enum ReadOutcome {
    Full,
    Partial,
    EofAtBoundary,
}

fn read_full<R: std::io::Read>(
    reader: &mut R,
    buf: &mut [u8],
) -> Result<ReadOutcome, std::io::Error> {
    let mut read = 0;
    while read < buf.len() {
        match reader.read(&mut buf[read..]) {
            Ok(0) => {
                if read == 0 {
                    return Ok(ReadOutcome::EofAtBoundary);
                }
                return Ok(ReadOutcome::Partial);
            }
            Ok(n) => read += n,
            Err(ref e) if e.kind() == std::io::ErrorKind::Interrupted => continue,
            Err(e) => return Err(e),
        }
    }
    Ok(ReadOutcome::Full)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn roundtrip(corr_id: u32, flags: u8, msg: &ShellMessage) {
        let frame = encode_frame(corr_id, flags, msg).expect("encode");
        assert!(frame.len() >= 4);
        let decoded_len = u32::from_be_bytes([frame[0], frame[1], frame[2], frame[3]]) as usize;
        assert_eq!(decoded_len + 4, frame.len(), "frame_len must match body");
        let (got_id, got_flags, got_msg) = decode_frame_body(&frame[4..]).expect("decode");
        assert_eq!(got_id, corr_id);
        assert_eq!(got_flags, flags);
        assert_eq!(&got_msg, msg);
    }

    #[test]
    fn request_roundtrip() {
        roundtrip(
            1,
            0,
            &ShellMessage::Request {
                cmd: "/bin/sh".to_string(),
                args: vec!["-c".into(), "echo hi".into()],
                env: vec!["FOO=bar".into()],
                cwd: Some("/workspace".into()),
                tty: false,
                rows: 24,
                cols: 80,
            },
        );
    }

    #[test]
    fn request_with_tty_roundtrip() {
        roundtrip(
            42,
            0,
            &ShellMessage::Request {
                cmd: "/bin/sh".to_string(),
                args: vec![],
                env: vec![],
                cwd: None,
                tty: true,
                rows: 40,
                cols: 120,
            },
        );
    }

    #[test]
    fn started_roundtrip() {
        roundtrip(7, 0, &ShellMessage::Started { pid: 12345 });
    }

    #[test]
    fn stdin_roundtrip() {
        roundtrip(
            9,
            0,
            &ShellMessage::Stdin {
                data_b64: "aGVsbG8=".into(),
            },
        );
    }

    #[test]
    fn stdout_roundtrip() {
        roundtrip(
            10,
            0,
            &ShellMessage::Stdout {
                data_b64: "d29ybGQ=".into(),
            },
        );
    }

    #[test]
    fn stderr_roundtrip() {
        roundtrip(
            10,
            0,
            &ShellMessage::Stderr {
                data_b64: "ZXJy".into(),
            },
        );
    }

    #[test]
    fn exited_roundtrip_terminal() {
        roundtrip(11, flags::FLAG_TERMINAL, &ShellMessage::Exited { code: 0 });
    }

    #[test]
    fn exited_nonzero_code() {
        roundtrip(11, flags::FLAG_TERMINAL, &ShellMessage::Exited { code: 42 });
    }

    #[test]
    fn resize_roundtrip() {
        roundtrip(
            12,
            0,
            &ShellMessage::Resize {
                rows: 100,
                cols: 200,
            },
        );
    }

    #[test]
    fn signal_roundtrip() {
        roundtrip(13, 0, &ShellMessage::Signal { signal: 15 });
    }

    #[test]
    fn error_roundtrip() {
        roundtrip(
            14,
            flags::FLAG_TERMINAL,
            &ShellMessage::Error {
                message: "spawn: ENOENT".into(),
            },
        );
    }

    #[test]
    fn encode_frame_has_expected_layout() {
        // Minimal payload: Started { pid: 0 }
        // serde_json produces exactly {"t":"started","pid":0} (no spaces).
        let frame =
            encode_frame(0xCAFEBABE, 0x01, &ShellMessage::Started { pid: 0 }).expect("encode");
        let frame_len = u32::from_be_bytes([frame[0], frame[1], frame[2], frame[3]]) as usize;
        assert_eq!(frame.len(), 4 + frame_len);
        assert_eq!(&frame[4..8], &[0xCA, 0xFE, 0xBA, 0xBE]);
        assert_eq!(frame[8], 0x01);
        let payload = std::str::from_utf8(&frame[9..]).unwrap();
        assert!(payload.starts_with("{\"t\":\"started\""), "got: {payload}");
    }

    #[test]
    fn decode_rejects_truncated_body() {
        let err = decode_frame_body(&[0, 0, 0, 0]).unwrap_err();
        assert!(
            matches!(err, ShellCodecError::LengthMismatch { .. }),
            "got {err:?}"
        );
    }

    #[test]
    fn validate_frame_len_rejects_small_and_large() {
        assert!(validate_frame_len(0).is_err());
        assert!(validate_frame_len((FRAME_HEADER_SIZE as u32) - 1).is_err());
        assert!(validate_frame_len((MAX_FRAME_SIZE as u32) + 1).is_err());
        assert!(validate_frame_len(FRAME_HEADER_SIZE as u32).is_ok());
        assert!(validate_frame_len(MAX_FRAME_SIZE as u32).is_ok());
    }

    #[test]
    fn read_frame_blocking_roundtrip() {
        let mut buf = Vec::new();
        write_frame_blocking(
            &mut buf,
            99,
            flags::FLAG_TERMINAL,
            &ShellMessage::Exited { code: 7 },
        )
        .unwrap();
        let mut cursor = std::io::Cursor::new(buf);
        let (id, fl, msg) = read_frame_blocking(&mut cursor)
            .unwrap()
            .expect("frame present");
        assert_eq!(id, 99);
        assert_eq!(fl, flags::FLAG_TERMINAL);
        assert_eq!(msg, ShellMessage::Exited { code: 7 });
        assert!(
            read_frame_blocking(&mut cursor).unwrap().is_none(),
            "expected clean EOF"
        );
    }

    #[test]
    fn read_frame_blocking_multiple_frames() {
        let mut buf = Vec::new();
        write_frame_blocking(&mut buf, 1, 0, &ShellMessage::Started { pid: 111 }).unwrap();
        write_frame_blocking(
            &mut buf,
            2,
            0,
            &ShellMessage::Stdout {
                data_b64: "YQ==".into(),
            },
        )
        .unwrap();
        write_frame_blocking(
            &mut buf,
            1,
            flags::FLAG_TERMINAL,
            &ShellMessage::Exited { code: 0 },
        )
        .unwrap();

        let mut cursor = std::io::Cursor::new(buf);
        let (id1, _, m1) = read_frame_blocking(&mut cursor).unwrap().unwrap();
        assert_eq!(id1, 1);
        assert!(matches!(m1, ShellMessage::Started { pid: 111 }));

        let (id2, _, m2) = read_frame_blocking(&mut cursor).unwrap().unwrap();
        assert_eq!(id2, 2);
        assert!(matches!(m2, ShellMessage::Stdout { .. }));

        let (id3, fl3, m3) = read_frame_blocking(&mut cursor).unwrap().unwrap();
        assert_eq!(id3, 1);
        assert_eq!(fl3, flags::FLAG_TERMINAL);
        assert!(matches!(m3, ShellMessage::Exited { code: 0 }));

        assert!(read_frame_blocking(&mut cursor).unwrap().is_none());
    }

    #[test]
    fn read_frame_blocking_partial_length_prefix_is_error() {
        let buf: Vec<u8> = vec![0, 0];
        let mut cursor = std::io::Cursor::new(buf);
        let err = read_frame_blocking(&mut cursor).unwrap_err();
        assert_eq!(err.kind(), std::io::ErrorKind::UnexpectedEof);
    }

    #[test]
    fn read_frame_blocking_rejects_oversized_frame() {
        let oversized = (MAX_FRAME_SIZE as u32) + 1;
        let buf = oversized.to_be_bytes().to_vec();
        let mut cursor = std::io::Cursor::new(buf);
        let err = read_frame_blocking(&mut cursor).unwrap_err();
        assert_eq!(err.kind(), std::io::ErrorKind::InvalidData);
    }

    #[test]
    fn encode_frame_rejects_oversized_payload() {
        let huge_env: Vec<String> = (0..200_000)
            .map(|i| format!("K{i}=VVVVVVVVVVVVVVVVVVVVVVVVVVVV"))
            .collect();
        let msg = ShellMessage::Request {
            cmd: "/bin/true".into(),
            args: vec![],
            env: huge_env,
            cwd: None,
            tty: false,
            rows: 24,
            cols: 80,
        };
        let err = encode_frame(0, 0, &msg).unwrap_err();
        assert!(
            matches!(err, ShellCodecError::InvalidFrameLength(_)),
            "got {err:?}"
        );
    }

    #[test]
    fn port_name_const_matches_spec() {
        // Guard against rename — host and guest agree via this const.
        assert_eq!(SHELL_PORT_NAME, "iii.exec");
    }

    #[test]
    fn flag_terminal_bit_is_stable() {
        // Wire-visible constant: changing this silently breaks existing peers.
        assert_eq!(flags::FLAG_TERMINAL, 0x01);
    }

    /// Helper that mirrors `encode_frame` for tests: takes the full wire
    /// frame (including the 4-byte `frame_len` prefix) and returns
    /// `(corr_id, flags, ShellMessage)`.
    fn decode_frame(frame: &[u8]) -> Result<(u32, u8, ShellMessage), ShellCodecError> {
        // frame[0..4] is the frame_len prefix; body starts at byte 4.
        decode_frame_body(&frame[4..])
    }

    #[test]
    fn fs_request_roundtrips() {
        let msg = ShellMessage::FsRequest(FsOp::Ls {
            path: "/workspace".into(),
        });
        let frame = encode_frame(7, 0, &msg).unwrap();
        let (corr_id, flag, decoded) = decode_frame(&frame).unwrap();
        assert_eq!(corr_id, 7);
        assert_eq!(flag, 0);
        assert_eq!(decoded, msg);
    }

    #[test]
    fn fs_chunk_carries_raw_bytes() {
        use base64::Engine;
        let msg = ShellMessage::FsChunk {
            data_b64: base64::engine::general_purpose::STANDARD.encode([0xDE, 0xAD, 0xBE, 0xEF]),
        };
        let frame = encode_frame(7, 0, &msg).unwrap();
        let (_, _, decoded) = decode_frame(&frame).unwrap();
        assert_eq!(decoded, msg);
    }

    #[test]
    fn fs_end_is_terminal_flagged() {
        let msg = ShellMessage::FsEnd;
        let frame = encode_frame(7, flags::FLAG_TERMINAL, &msg).unwrap();
        let (_, flag, decoded) = decode_frame(&frame).unwrap();
        assert_eq!(flag & flags::FLAG_TERMINAL, flags::FLAG_TERMINAL);
        assert_eq!(decoded, msg);
    }

    #[test]
    fn fs_response_carries_result() {
        let msg = ShellMessage::FsResponse(FsResult::Ls {
            entries: vec![FsEntry {
                name: "foo.py".into(),
                is_dir: false,
                size: 1234,
                mode: "0644".into(),
                mtime: 1_714_000_000,
                is_symlink: false,
            }],
        });
        let frame = encode_frame(7, flags::FLAG_TERMINAL, &msg).unwrap();
        let (_, _, decoded) = decode_frame(&frame).unwrap();
        assert_eq!(decoded, msg);
    }

    #[test]
    fn fs_error_carries_code_and_message() {
        let msg = ShellMessage::FsError {
            code: "S211".into(),
            message: "path not found".into(),
        };
        let frame = encode_frame(7, flags::FLAG_TERMINAL, &msg).unwrap();
        let (_, _, decoded) = decode_frame(&frame).unwrap();
        assert_eq!(decoded, msg);
    }

    /// Forward-compat: an FsRequest carrying an unknown `op` tag (e.g.
    /// from a newer host hitting an older supervisor) must decode-fail
    /// rather than silently land in some default variant. The supervisor
    /// translates the decode error into an `FsError { code: "S219" }`
    /// frame on the wire so the host gets a typed signal.
    #[test]
    fn unknown_fs_op_is_rejected_by_decoder() {
        let payload = br#"{"t":"fs_request","op":"teleport","path":"/x"}"#;
        let total_len = FRAME_HEADER_SIZE + payload.len();
        let mut frame = Vec::with_capacity(4 + total_len);
        frame.extend_from_slice(&(total_len as u32).to_be_bytes());
        frame.extend_from_slice(&7u32.to_be_bytes()); // corr_id
        frame.push(0); // flags
        frame.extend_from_slice(payload);

        let err = decode_frame(&frame).unwrap_err();
        assert!(
            matches!(err, ShellCodecError::Deserialize(_)),
            "expected Deserialize error, got: {err:?}"
        );
    }

    // ──────────────────────────────────────────────────────────────────────
    // FsMatch / FsSedFileResult: canonical serde key is `path`, with
    // `#[serde(alias = "file")]` so older wire payloads still decode.
    // ──────────────────────────────────────────────────────────────────────

    #[test]
    fn fs_match_deserializes_legacy_file_alias() {
        let json = r#"{"file":"/x","line":1,"content":"hi"}"#;
        let m: FsMatch = serde_json::from_str(json).expect("decode legacy");
        assert_eq!(m.path, "/x");
    }

    #[test]
    fn fs_match_deserializes_canonical_path() {
        let json = r#"{"path":"/x","line":1,"content":"hi"}"#;
        let m: FsMatch = serde_json::from_str(json).expect("decode canonical");
        assert_eq!(m.path, "/x");
    }

    #[test]
    fn fs_match_serializes_as_path_not_file() {
        let m = FsMatch {
            path: "/x".into(),
            line: 1,
            content: "hi".into(),
        };
        let v: serde_json::Value = serde_json::to_value(&m).unwrap();
        assert!(v.get("path").is_some(), "expected `path` key, got: {v}");
        assert!(v.get("file").is_none(), "expected no `file` key, got: {v}");
    }

    #[test]
    fn fs_sed_file_result_deserializes_legacy_file_alias() {
        let json = r#"{"file":"/x","replacements":2,"success":true}"#;
        let r: FsSedFileResult = serde_json::from_str(json).expect("decode legacy");
        assert_eq!(r.path, "/x");
        assert_eq!(r.replacements, 2);
        assert!(r.success);
    }

    #[test]
    fn fs_sed_file_result_deserializes_canonical_path() {
        let json = r#"{"path":"/x","replacements":2,"success":true}"#;
        let r: FsSedFileResult = serde_json::from_str(json).expect("decode canonical");
        assert_eq!(r.path, "/x");
    }

    // ──────────────────────────────────────────────────────────────────────
    // FsOp::Sed dual-form serde: legacy `files:[…]` payloads must keep
    // decoding, and the new `path` + `recursive` + `*_glob` form must
    // round-trip with `#[serde(default)]` on every new field.
    // ──────────────────────────────────────────────────────────────────────

    #[test]
    fn fs_op_sed_legacy_files_only_payload_decodes() {
        // Wire payload an old guest would send: only `files`, no
        // `path`/`recursive`/`*_glob`.
        let json = r#"{
            "op":"sed",
            "files":["/x/a.py","/x/b.py"],
            "pattern":"hello",
            "replacement":"world",
            "regex":false,
            "first_only":false,
            "ignore_case":false
        }"#;
        let op: FsOp = serde_json::from_str(json).expect("decode legacy sed");
        match op {
            FsOp::Sed {
                files,
                path,
                recursive,
                include_glob,
                exclude_glob,
                ..
            } => {
                assert_eq!(files, vec!["/x/a.py".to_string(), "/x/b.py".to_string()]);
                assert!(path.is_none(), "path should default to None");
                // recursive defaults to true via default_recursive_true.
                assert!(recursive, "recursive should default to true");
                assert!(include_glob.is_empty());
                assert!(exclude_glob.is_empty());
            }
            other => panic!("expected Sed, got {other:?}"),
        }
    }

    #[test]
    fn fs_op_sed_path_form_with_globs_roundtrips() {
        let original = FsOp::Sed {
            files: Vec::new(),
            path: Some("/workspace".into()),
            recursive: true,
            include_glob: vec!["*.py".into()],
            exclude_glob: vec!["target/*".into()],
            pattern: "foo".into(),
            replacement: "bar".into(),
            regex: false,
            first_only: false,
            ignore_case: false,
        };
        let encoded = serde_json::to_string(&original).expect("encode");
        let decoded: FsOp = serde_json::from_str(&encoded).expect("decode");
        assert_eq!(decoded, original);
    }

    #[test]
    fn fs_sed_file_result_serializes_as_path_not_file() {
        let r = FsSedFileResult {
            path: "/x".into(),
            replacements: 2,
            success: true,
            error: None,
        };
        let v: serde_json::Value = serde_json::to_value(&r).unwrap();
        assert!(v.get("path").is_some(), "expected `path` key, got: {v}");
        assert!(v.get("file").is_none(), "expected no `file` key, got: {v}");
    }
}
