import type { MapEdge, MapNode, MapNodeInfo } from '@lib/components/diagrams/SystemMap'

export const MAP_NODES: MapNode[] = [
  {
    id: 'config',
    x: 36,
    y: 256,
    w: 184,
    h: 96,
    title: 'codegen.yml',
    sub: 'output → spec map',
    kind: 'external',
  },
  {
    id: 'codegen',
    x: 326,
    y: 196,
    w: 308,
    h: 216,
    title: 'codegen',
    sub: 'one rust binary · cli + worker',
    kind: 'primary',
  },
  {
    id: 'engine',
    x: 784,
    y: 92,
    w: 214,
    h: 122,
    title: 'engine',
    sub: 'engine::*::list / ::info',
    kind: 'secondary',
  },
  {
    id: 'output',
    x: 784,
    y: 296,
    w: 214,
    h: 96,
    title: 'generated files',
    sub: '*.ts  *.rs  *.py',
    kind: 'secondary',
  },
  {
    id: 'consumer',
    x: 784,
    y: 452,
    w: 214,
    h: 96,
    title: 'your code · harness',
    sub: 'imports the typed client',
    kind: 'external',
  },
]

export const MAP_EDGES: MapEdge[] = [
  {
    id: 'config-codegen',
    from: 'config',
    to: 'codegen',
    d: 'M 220 304 L 326 304',
    label: 'config',
    lx: 273,
    ly: 295,
    anchor: 'middle',
  },
  {
    id: 'codegen-engine',
    from: 'codegen',
    to: 'engine',
    d: 'M 634 250 C 706 250, 724 176, 784 162',
    label: 'iii.trigger',
    lx: 688,
    ly: 206,
    anchor: 'middle',
    dur: 2,
  },
  {
    id: 'engine-codegen',
    from: 'engine',
    to: 'codegen',
    d: 'M 784 132 C 700 116, 690 206, 634 224',
    label: 'json schema',
    lx: 690,
    ly: 138,
    anchor: 'middle',
    dashed: true,
  },
  {
    id: 'codegen-output',
    from: 'codegen',
    to: 'output',
    d: 'M 634 344 C 706 344, 720 344, 784 344',
    label: 'emit + write',
    lx: 690,
    ly: 335,
    anchor: 'middle',
    dur: 2,
  },
  {
    id: 'output-consumer',
    from: 'output',
    to: 'consumer',
    d: 'M 891 392 L 891 452',
    label: 'import',
    lx: 901,
    ly: 426,
    anchor: 'start',
  },
]

export const MAP_INFO: Record<string, MapNodeInfo> = {
  config: {
    id: 'config',
    kindLabel: 'your input',
    role: 'a graphql-codegen-style map of output path → generation spec. the one file you write.',
    sections: [
      {
        heading: 'each output declares',
        items: [
          { name: 'language', desc: 'typescript · javascript · rust · python' },
          { name: 'mode', desc: 'types · functions · triggers' },
          { name: 'workers / functions / triggers', desc: 'glob selectors over the catalog' },
          { name: 'iii_instance', desc: 'import a singleton, or take it as an argument' },
        ],
      },
    ],
    note: 'the engine address is never in this file; it comes from --url or $III_URL.',
  },
  codegen: {
    id: 'codegen',
    kindLabel: 'the worker + cli',
    role: 'one binary, two front doors over the same pipeline: select → discover → map → emit → write.',
    sections: [
      {
        heading: 'exposes',
        items: [
          { name: 'codegen::generate', desc: 'run a config and write the files' },
          { name: 'codegen::preview', desc: 'return the generated source, write nothing' },
          { name: 'codegen::languages', desc: 'what this build can emit' },
        ],
      },
      {
        heading: 'cli',
        items: [
          { name: 'codegen generate --config', desc: 'the golden path' },
          { name: '--check', desc: 'fail ci if a file would change' },
        ],
      },
    ],
    install: 'codegen generate --config codegen.yml',
  },
  engine: {
    id: 'engine',
    kindLabel: 'the source of truth',
    role: 'already describes every connected worker in json schema, derived from real worker types. codegen invents no schema of its own.',
    sections: [
      {
        heading: 'discovery surface',
        dotted: true,
        items: [
          { name: 'engine::functions::list', desc: 'enumerate the catalog' },
          { name: 'engine::functions::info', desc: 'request_schema + response_schema' },
          { name: 'engine::triggers::info', desc: 'config · payload · return schema' },
        ],
      },
    ],
    note: 'schemas are schemars / draft-7 json schema, registered by each worker at startup.',
  },
  output: {
    id: 'output',
    kindLabel: 'generated files',
    role: 'idiomatic types, function wrappers, and trigger helpers, committed to your repo.',
    sections: [
      {
        heading: 'every file is',
        items: [
          { name: 'banner', desc: 'code generated by iii codegen · do not edit' },
          { name: 'deterministic', desc: 'sorted + stable; a rerun is a no-op diff' },
        ],
      },
    ],
    note: 'one catalog projects into every target language at once.',
  },
  consumer: {
    id: 'consumer',
    kindLabel: 'your code · harness',
    role: 'imports the generated client and calls workers with typed wrappers instead of raw strings.',
    bullets: [
      'a renamed field is now a compile error, not a production 404.',
      'binding harness::turn-completed is a typed harness.onTurnCompleted, not an any.',
    ],
  },
}
